version: "2"

linters:
  enable:
    - asasalint
    - errcheck
    - errname
    - gocritic
    - govet
    - ineffassign
    - prealloc
    - revive
    - staticcheck
    - unused
    - whitespace

formatters:
  enable:
    - gofmt
